import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

live_config_reload = true

[window]
dimensions = { columns = 90, lines = 23 }
# decorations = "None"
padding = { x = 5, y = 0 }
dynamic_padding = true
opacity = 0.90

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
size = 11

[cursor]
style = { shape = "Underline", blinking = "On" }
