#!/bin/bash

function get_volume {
    pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | sed 's/%//'
}

function increase_volume {
    current_volume=$(get_volume)
    if [ $current_volume -le 80 ]; then
        pactl -- set-sink-volume @DEFAULT_SINK@ +10%
    elif [ $current_volume -lt 100 ]; then
        pactl -- set-sink-volume @DEFAULT_SINK@ 100%
    fi
}

function decrease_volume {
    pactl -- set-sink-volume @DEFAULT_SINK@ -10%
}

function toggle_mute {
    pactl set-sink-mute @DEFAULT_SINK@ toggle
}

case $1 in
    up)
        increase_volume
        ;;
    down)
        decrease_volume
        ;;
    toggle_mute)
        toggle_mute
        ;;
    *)
        echo "Usage: $0 {up|down|toggle_mute}"
        exit 1
        ;;
esac
