theme = "catppuccin_macchiato"

[editor]
mouse = false
bufferline = "multiple"
middle-click-paste = false
completion-replace = true
true-color = true
color-modes = true

# popup-border = "all"
# line-number = "relative"
# preview-completion-insert = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "file-type", "position", "position-percentage", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-x = [":buffer-close"]
C-s = ":w"
"C-ret" = "code_action"
